### ISSUE TITLE
是 GNU(GNU's Not Unix!) 而不是 GUN

### ISSUE THREAD

**Issue by jaywhen** [Quanuanc/quanuanc.github.io#1]
在 [文章](https://quanuanc.github.io/posts/vscode-wsl-cpp/) 中:

> 在本教程中，你将配置 Visual Studio Code，在 Windows Linux 子系统（WSL） Ubuntu 中使用 GCC C++编译器（g++）和 GDB > 调试器。GCC 代表了 GUN 编译器集合；GDB 是 GUN 调试器。WSL 是 Windows 中的 Linux 环境，它直接在计算机硬件上运行，> 而不是在虚拟机中。

此段落中的 GUN 都应为 GNU

**Comment by quanuanc** [comment]
@jaywhen 感谢你的提醒，明天我再改正一下 ^^
